### ISSUE TITLE
Just in case, not a bug

### ISSUE THREAD

**Issue by andy-shev** [kmarinushkin/linux#1]
GitHub has an official mirror of Torvalds' tree, so, you may decrease drastically the size of your repo by using that mirror.

**Comment by kmarinushkin** [comment]
@andy-shev that's a good point. I will do that, thanks

**Comment by kmarinushkin** [comment]
@andy-shev 

According to the github's help [1],

> A fork is a copy of a repository that you manage

For me it looks like the github's fork is still a full copy, not a link. So, forking will not optimize the size of the repo

[1] https://help.github.com/articles/about-forks/

**Comment by andy-shev** [comment]
Here is some points https://stackoverflow.com/questions/11974686/explanation-of-github-fork-and-how-they-store-files, though for sure they optimize forks, to know how it would be better to look at the actual code.

So, my point is when one forks from another project in GH, it would reduce storage use, otherwise might not (although they might be clever today to hook by the remote URL and convert to local fork internally).

**Comment by kmarinushkin** [comment]
I see what you mean. Yes, this looks logical.
Anyway I feel better to clone git.kernel.org, instead of github.com.
I will check the `--mirror` option, maybe it can optimize the storage for me.

**Comment by andy-shev** [comment]
@torvalds' version is official on GH as well.
